name: CI/CD Pipeline for Salesforce with SonarCloud

on:
  push:
    branches:
      - 'WI-*'

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Create JWT Key File
        run: echo "${{ secrets.JWT_PRIVATE_KEY }}" > assets/server.key

      - name: Authorize Dev Hub (Production)
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_PROD }} --jwtkeyfile assets/server.key --username ${{ secrets.SALESFORCE_PROD_USERNAME }} --setdefaultdevhubusername --setalias prod

      - name: Authorize Developer Org
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_DEVELOPER }} --jwtkeyfile assets/server.key --username ${{ secrets.DEVELOPER_SANDBOX_USERNAME }} --setalias developer

      - name: Generate Package.xml for Changed Components
        id: generate_package
        run: |
          mkdir -p ./manifest
          git diff --name-only HEAD^..HEAD > all-changed-components.txt
          cat all-changed-components.txt
          grep "\.cls$" all-changed-components.txt | sed 's|force-app/main/default/classes/||' > changed-components.txt
          cat changed-components.txt
          if [ -s changed-components.txt ]; then
            echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > ./manifest/package.xml
            echo '<Package xmlns="http://soap.sforce.com/2006/04/metadata">' >> ./manifest/package.xml
            echo '  <types>' >> ./manifest/package.xml
            while read component; do
              echo "    <members>${component%.cls}</members>" >> ./manifest/package.xml
            done < changed-components.txt
            echo '    <name>ApexClass</name>' >> ./manifest/package.xml
            echo '  </types>' >> ./manifest/package.xml
            echo '  <version>53.0</version>' >> ./manifest/package.xml
            echo '</Package>' >> ./manifest/package.xml
            cat ./manifest/package.xml
            echo "::set-output name=changed::true"
          else
            echo "No Apex classes were changed."
            echo "::set-output name=changed::false"
          fi

      - name: Skip if no Apex classes changed
        if: steps.generate_package.outputs.changed == 'false'
        run: echo "No Apex classes changed. Skipping deployment and tests."
        continue-on-error: true

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Extract Test Class Names from Package.xml
        id: extract_tests
        run: |
          if [ -f ./manifest/package.xml ]; then
            test_classes=$(xmlstarlet sel -t -v "//members" -o "," ./manifest/package.xml | sed 's/,$//')
            echo "::set-output name=test_classes::$test_classes"
          else
            echo "::set-output name=test_classes::"
          fi

      - name: Validate Deployment using Manifest
        if: steps.generate_package.outputs.changed == 'true'
        id: validate_deployment
        run: |
          sfdx force:source:deploy --checkonly --manifest ./manifest/package.xml --targetusername developer --testlevel RunSpecifiedTests --runtests TemperatureConverterTest

      - name: Deploy Source to Developer Org
        if: steps.generate_package.outputs.changed == 'true'
        id: deploy_source
        run: |
          sfdx force:source:deploy --manifest ./manifest/package.xml --targetusername developer --testlevel RunSpecifiedTests --runtests TemperatureConverterTest

      - name: Run Apex Tests and Generate Report
        if: steps.deploy_source.outcome == 'success' || steps.validate_deployment.outcome == 'success'
        run: |
          result=$(sfdx force:apex:test:run --resultformat json --wait 10 --targetusername developer | tee result.json)
          testrunid=$(jq -r '.testRunId' result.json)
          sfdx force:apex:test:report --testrunid "$testrunid" --resultformat json --outputdir test-results --targetusername developer

      - name: Convert Coverage Report to XML
        if: steps.deploy_source.outcome == 'success' || steps.validate_deployment.outcome == 'success'
        run: |
          sfdx force:apex:test:report --codecoverage --resultformat json --outputdir test-results --targetusername developer
          # Convert to SonarQube's format
          sfdx sfpowerkit:apex:test:coverage:report --resultfile test-results/test-result-codecoverage.json --reporttype xml --outputdir test-results

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: '-Xmx1024m'
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        with:
          args: >
            -Dsonar.projectKey=SNHS1998_SonarQube-DevOpsCenter-Public
            -Dsonar.apex.coverage.reportPaths=test-results/apex-codecoverage.xml

      - name: Check SonarQube Quality Gate
        id: quality_gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          status=$(curl -s "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=SNHS1998_SonarQube-DevOpsCenter-Public" -u "${SONAR_TOKEN}:")
          coverage=$(echo "$status" | jq -r '.projectStatus.conditions[] | select(.metricKey == "new_coverage") | .actualValue')
          echo "Current New Code Coverage: $coverage%"
          if (( $(echo "$coverage == null" | bc -l) )); then
            echo "New code coverage information is not available."
            exit 1
          elif (( $(echo "$coverage < 80" | bc -l) )); then
            echo "New code coverage is less than 80%. Failing the build."
            exit 1
          else
            echo "New code coverage is sufficient. Proceeding with the build."
          fi

      - name: Fail build on Quality Gate status
        if: steps.quality_gate.outcome != 'success'
        run: exit 1
