name: CI/CD Pipeline for Salesforce with SonarCloud

on:
  push:
    branches:
      - 'WI-*'

jobs:
  generate_and_validate:
    runs-on: ubuntu-latest
    outputs:
      test_classes: ${{ steps.set_test_classes.outputs.test_classes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Generate Package.xml for Changed Components
        id: generate_package
        run: |
          mkdir -p ./manifest
          git diff --name-only HEAD^..HEAD > all-changed-components.txt
          grep "\.cls$" all-changed-components.txt | sed 's|force-app/main/default/classes/||' > changed-components.txt
          if [ -s changed-components.txt ]; then
            echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > ./manifest/package.xml
            echo '<Package xmlns="http://soap.sforce.com/2006/04/metadata">' >> ./manifest/package.xml
            echo '  <types>' >> ./manifest/package.xml
            while read component; do
              echo "    <members>${component%.cls}</members>" >> ./manifest/package.xml
            done < changed-components.txt
            echo '    <name>ApexClass</name>' >> ./manifest/package.xml
            echo '  </types>' >> ./manifest/package.xml
            echo '  <version>53.0</version>' >> ./manifest/package.xml
            echo '</Package>' >> ./manifest/package.xml
            cat ./manifest/package.xml
            test_classes=$(xmlstarlet sel -t -v "//members" -o "," ./manifest/package.xml | sed 's/,$//')
            echo "::set-output name=test_classes::$test_classes"
          else
            echo "::set-output name=test_classes::"
          fi

      - name: Set test classes output
        id: set_test_classes
        run: |
          echo "test_classes=${{ steps.generate_package.outputs.test_classes }}" >> $GITHUB_ENV

      - name: Create JWT Key File
        run: echo "${{ secrets.JWT_PRIVATE_KEY }}" > assets/server.key

      - name: Authorize Dev Hub (Production)
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_PROD }} --jwtkeyfile assets/server.key --username ${{ secrets.SALESFORCE_PROD_USERNAME }} --setdefaultdevhubusername --setalias prod

      - name: Authorize Developer Org
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_DEVELOPER }} --jwtkeyfile assets/server.key --username ${{ secrets.DEVELOPER_SANDBOX_USERNAME }} --setalias developer

      - name: Validate Deployment using Manifest
        if: steps.set_test_classes.outputs.test_classes != ''
        run: |
          sfdx force:source:deploy --checkonly --manifest ./manifest/package.xml --targetusername developer --testlevel RunSpecifiedTests --runtests ${{ steps.set_test_classes.outputs.test_classes }}

  deploy_and_test:
    runs-on: ubuntu-latest
    needs: generate_and_validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Create JWT Key File
        run: echo "${{ secrets.JWT_PRIVATE_KEY }}" > assets/server.key

      - name: Authorize Developer Org
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_DEVELOPER }} --jwtkeyfile assets/server.key --username ${{ secrets.DEVELOPER_SANDBOX_USERNAME }} --setalias developer

      - name: Deploy Source to Developer Org
        if: needs.generate_and_validate.outputs.test_classes != ''
        run: |
          sfdx force:source:deploy --manifest ./manifest/package.xml --targetusername developer --testlevel RunSpecifiedTests --runtests ${{ needs.generate_and_validate.outputs.test_classes }}

      - name: Run Apex Tests and Generate Report
        if: needs.generate_and_validate.outputs.test_classes != ''
        run: |
          result=$(sfdx force:apex:test:run --resultformat json --wait 10 --targetusername developer | tee result.json)
          testrunid=$(jq -r '.testRunId' result.json)
          sfdx force:apex:test:report --testrunid "$testrunid" --outputdir test-results --targetusername developer

      - name: Convert Coverage Report to XML
        if: needs.generate_and_validate.outputs.test_classes != ''
        run: |
          sfdx force:apex:test:report --codecoverage --outputdir test-results --targetusername developer

      - name: Upload Coverage Report
        if: needs.generate_and_validate.outputs.test_classes != ''
        uses: actions/upload-artifact@v2
        with:
          name: apex-codecoverage
          path: test-results/

  sonarqube:
    runs-on: ubuntu-latest
    needs: deploy_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Coverage Report
        uses: actions/download-artifact@v2
        with:
          name: apex-codecoverage
          path: test-results/

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: '-Xmx1024m'
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        with:
          args: >
            -Dsonar.projectKey=SNHS1998_SonarQube-DevOpsCenter-Public
            -Dsonar.apex.coverage.reportPaths=test-results/apex-codecoverage.xml

      - name: Check SonarQube Quality Gate
        id: quality_gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          status=$(curl -s "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=SNHS1998_SonarQube-DevOpsCenter-Public" -u "${SONAR_TOKEN}:")
          quality_gate=$(echo "$status" | jq -r '.projectStatus.status')
          echo "quality_gate_status=$quality_gate" >> $GITHUB_ENV

      - name: Fail the build if Quality Gate fails
        if: env.quality_gate_status != 'OK'
        run: exit 1
