name: CI/CD Pipeline for Salesforce with SonarCloud

on:
  push:
    branches:
      - 'WI-*'

jobs:
  generate_and_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Create JWT Key File
        run: echo "${{ secrets.JWT_PRIVATE_KEY }}" > assets/server.key

      - name: Authorize Dev Hub (Production)
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_PROD }} --jwtkeyfile assets/server.key --username ${{ secrets.SALESFORCE_PROD_USERNAME }} --setdefaultdevhubusername --setalias prod

      - name: Authorize Developer Org
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_DEVELOPER }} --jwtkeyfile assets/server.key --username ${{ secrets.DEVELOPER_SANDBOX_USERNAME }} --setalias developer

      - name: Retrieve Changed Components
        id: retrieve_changes
        run: |
          mkdir -p ./manifest
          git diff --name-only HEAD^..HEAD > all-changed-components.txt
          grep "\.cls$" all-changed-components.txt | sed 's|force-app/main/default/classes/||' > changed-components.txt

      - name: Run Salesforce CLI to Fetch Test Classes
        id: fetch_test_classes
        run: |
          # Example command to fetch test classes, adjust as per your structure
          test_classes=$(grep -oP '(?<=force-app/main/default/classes/).*(?=.cls)' changed-components.txt | paste -sd "," -)
          echo "DEBUG: Test classes found: $test_classes"
          echo "::set-output name=test_classes::$test_classes"

      - name: Validate Deployment using Test Classes
        if: ${{ steps.fetch_test_classes.outputs.test_classes != '' }}
        run: |
          echo "Validating deployment using specified test classes..."
          sfdx force:source:deploy --checkonly --sourcepath force-app/main/default --targetusername developer --testlevel RunSpecifiedTests --runtests ${{ steps.fetch_test_classes.outputs.test_classes }}
